config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :comments do
    member do
      post :reply
      post :dislike
      post :like
    end

  end
  root 'comments#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to  :user
  has_one     :parent,    -> { where("parent_id > 0") }, class_name: 'Comment',foreign_key: :parent_id
  has_many    :replies,   class_name: 'Comment', foreign_key: :parent_id, dependent: :destroy
  has_many    :votes ,    class_name: 'CommentVote',dependent: :destroy

  validates :content,   presence: true
end

app/models/comment_vote.rb
class CommentVote < ApplicationRecord
  belongs_to :user
  belongs_to :comment
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :votes, class_name: 'CommentVote'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_comment, only: [:show, :reply, :destroy, :like, :edit, :update, :dislike]

  def index
    @comment = Comment.new 
    @comments = Comment.where(parent_id: 0).order('id asc')
  end

  def create
    @comment = Comment.new(comment_params)
    
    respond_to do |format|
      if @comment.save
        format.html { redirect_to @comment }
        format.js   {}
      else 
        format.html { render :new}
        format.js { }
      end
    end
  end 

  def update
    respond_to do |format|
      if @comment.update(comment_params)
        format.html { redirect_to  @comment }
        format.js   { }
      else 
        format.html { render :edit}
        format.js   { }
      end
    end
  end

  def destroy 
    @comment.destroy
    redirect_to comments_url
  end

  def reply; end  

  def like
    @comment.votes.create({user_id: current_user.id})
    redirect_to comments_url
  end 

  def dislike
    @comment.votes.where({user_id: current_user.id}).destroy_all
    redirect_to comments_url
  end

  private
  def comment_params
    data = params.require(:comment).permit(:parent_id, :content) 
    data[:user_id] = current_user.id 
    data
  end

  def set_comment
    @comment = Comment.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def liked(comment, user)
    if comment.votes.where({user_id: user.id}).count > 0
      'dislike'
    else
      'like'
    end
  end

  def format_date(date)
    date.strftime('%b %d, %Y')
  end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/comments/_comment.html.slim
.comments-comment-container id="comment-#{comment.id}"
  .comment-inner
    .thumb
      = image_tag 'default.jpg'
    .detail
      strong.author
        = link_to comment.user.email
      .content
        = simple_format(comment.content)
      ul.caption
        li
          = link_to 'reply',  [:reply, comment] , remote: true, class: 'comment-reply', 'data-index': comment.id, method: :post
        li
          = link_to 'edit',   [:edit, comment] , remote: true, class: 'comment-reply', 'data-index': comment.id
        li
          = link_to 'Delete', comment_path(comment),
              method: :delete,
              data: { confirm: 'Are you sure?' }
        li
          - like = user_signed_in?? liked(comment, current_user) : 'like'
          = link_to like, [like, comment], method: :post
        li
          = format_date(comment.created_at)
    .reply-inner
      - if comment.replies.any?
          - comment.replies.each do |cm|
            = render 'comment', comment: cm

app/views/comments/_form.html.slim
div class='comments-form-container comment-form-number-#{index}'
  = simple_form_for comment, remote: true, defaults: { label: false } do |f|
    .form-error
      = f.error_notification
    .input-cover 
      = f.input :content
      = f.input :parent_id, :as => :hidden
    = f.button :button, 'Comment', class: 'btn-submit' 

app/views/comments/create.js.erb
var index = ('<%=@comment.parent_id%>');
if (index == 0) {
  $('.comment-form-number-root').before('<%= j render 'comment', :comment => @comment %>');
  $('.comment-form-number-root textarea').val('');
}
else{
  $('#comment-' + index + ' > .comment-inner > .reply-inner').append('<%= j render 'comment', :comment => @comment %>');
  $('.comment-form-number-' + index + ' textarea').val('');
}

app/views/comments/edit.js.erb
var index = ('<%=@comment.id%>'); 
$('#comment-' + index + ' > .comment-inner .comment-form-number-' + index).remove();
$('#comment-' + index + ' > .comment-inner > .detail').after('<%= j (render 'form', comment: @comment, index: @comment.id) %>')

app/views/comments/index.html.slim
#comments-index-container
  - @comments.each do |comment| 
    = render 'comment', comment: comment
  = render 'form', comment: Comment.new, index: 'root'

app/views/comments/reply.js.erb
var index = ('<%=@comment.id%>');
$('#comment-' + index + ' > .comment-inner .comment-form-number-' + index).remove();
$('#comment-' + index + ' > .comment-inner > .detail').after('<%= j (render 'form', comment: @comment.replies.new, index: @comment.id) %>');

app/views/comments/update.js.erb
var index = ('<%=@comment.id%>');
$('#comment-' + index).html('<%= escape_javascript(render 'comment', :comment => @comment) %>');
$('.comment-form-number-' + i).remove(); 

app/views/layouts/_head.html.slim
title RailsTest10
= csrf_meta_tags
= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
= javascript_include_tag 'application', 'data-turbolinks-track': 'reload'

app/views/layouts/application.html.slim
doctype html
html
  = render 'layouts/head'
  body 
    #main
      = yield